"""Owns ~/.config/hypr/hyprgui/state.json (what the user has changed through
this app) and regenerates ~/.config/hypr/hyprgui.lua from it on every save.

hyprgui.lua is fully owned by this app - it is overwritten wholesale on
every change and carries a loud header saying so. It never touches the
user's own hyprland.lua except for the one `require("hyprgui")` line that
ensure_require() inserts once.
"""
import json
import re
import time
from pathlib import Path

HYPR_DIR = Path.home() / ".config/hypr"
STATE_DIR = HYPR_DIR / "hyprgui"
STATE_PATH = STATE_DIR / "state.json"
LUA_PATH = HYPR_DIR / "hyprgui.lua"

_EMPTY_STATE = {
    "options": {},       # dotted key -> already-serialized value string (same form hyprctl keyword takes)
    "option_kind": {},   # dotted key -> widget kind, so we know bool/int/float vs string when emitting Lua
    "monitors": [],       # list of dict (MonitorSpec fields, all string-serialized)
    "env": {},            # NAME -> value string
    "autostart": [],      # list of shell command strings
    "binds": [],          # list of {"combo": "SUPER + Q", "dispatcher_lua": 'hl.dsp.exec_cmd("kitty")', "opts": {..bool flags..}, "desc": "..."}
    "window_rules": [],   # list of {"name": str, "match": {k:v str}, "fields": {k: v-string}}
    "layer_rules": [],
    "workspace_rules": [],
    "permissions": [],    # list of {"binary": regex str, "type": "screencopy"|"keyboard"|"plugin", "mode": "allow"|"deny"|"ask"}
}


def load_state() -> dict:
    if not STATE_PATH.exists():
        return json.loads(json.dumps(_EMPTY_STATE))
    try:
        data = json.loads(STATE_PATH.read_text())
    except json.JSONDecodeError:
        return json.loads(json.dumps(_EMPTY_STATE))
    for k, v in _EMPTY_STATE.items():
        data.setdefault(k, json.loads(json.dumps(v)))
    return data


def save_state(state: dict) -> None:
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_PATH.write_text(json.dumps(state, indent=2, sort_keys=True))
    LUA_PATH.write_text(_render_lua(state))


def _lua_str(s: str) -> str:
    escaped = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def _lua_scalar(value: str, kind: str) -> str:
    if kind == "bool":
        return "true" if value in ("true", "1", "yes") else "false"
    if kind in ("int", "float"):
        return value
    return _lua_str(value)


def _set_nested(tree: dict, dotted_key: str, leaf_value: str) -> None:
    parts = dotted_key.split(".")
    node = tree
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    node[parts[-1]] = leaf_value


def _render_table(tree: dict, indent: int) -> list[str]:
    pad = "    " * indent
    lines = []
    for key in sorted(tree):
        value = tree[key]
        if isinstance(value, dict):
            lines.append(f"{pad}{key} = {{")
            lines.extend(_render_table(value, indent + 1))
            lines.append(f"{pad}}},")
        else:
            lines.append(f"{pad}{key} = {value},")
    return lines


def _render_lua(state: dict) -> str:
    out = [
        "-- AUTO-GENERATED by hyprgui. Do not hand-edit - your changes will be",
        "-- overwritten the next time you use the app. Edit through the GUI,",
        f"-- or edit hyprland.lua directly for anything unmanaged by hyprgui.",
        f"-- Last written: {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]

    for perm in state["permissions"]:
        out.append(
            "hl.permission({ binary = "
            f'{_lua_str(perm["binary"])}, type = {_lua_str(perm["type"])}, '
            f'mode = {_lua_str(perm["mode"])} }})'
        )
    if state["permissions"]:
        out.append("")

    if state["options"]:
        tree: dict = {}
        for key, value in state["options"].items():
            kind = state["option_kind"].get(key, "string")
            _set_nested(tree, key, _lua_scalar(value, kind))
        out.append("hl.config({")
        out.extend(_render_table(tree, 1))
        out.append("})")
        out.append("")

    for mon in state["monitors"]:
        out.append("hl.monitor({")
        for k, v in mon.items():
            out.append(f"    {k} = {_lua_str(v) if not _is_lua_literal(v) else v},")
        out.append("})")
    if state["monitors"]:
        out.append("")

    for name, value in state["env"].items():
        out.append(f'hl.env({_lua_str(name)}, {_lua_str(value)})')
    if state["env"]:
        out.append("")

    if state["autostart"]:
        out.append('hl.on("hyprland.start", function()')
        for cmd in state["autostart"]:
            out.append(f"    hl.exec_cmd({_lua_str(cmd)})")
        out.append("end)")
        out.append("")

    for b in state["binds"]:
        opts = b.get("opts") or {}
        opt_pairs = ", ".join(f"{k} = {'true' if v else 'false'}" for k, v in opts.items() if v)
        opts_arg = f", {{ {opt_pairs} }}" if opt_pairs else ""
        out.append(f'hl.bind({_lua_str(b["combo"])}, {b["dispatcher_lua"]}{opts_arg})')
    if state["binds"]:
        out.append("")

    for kind, rule_fn in (
        ("window_rules", "window_rule"),
        ("layer_rules", "layer_rule"),
        ("workspace_rules", "workspace_rule"),
    ):
        for rule in state[kind]:
            out.append(f"hl.{rule_fn}({{")
            if rule.get("name"):
                out.append(f'    name = {_lua_str(rule["name"])},')
            match = rule.get("match") or {}
            if match:
                out.append("    match = {")
                for k, v in match.items():
                    out.append(f"        {k} = {_lua_str(v) if not _is_lua_literal(v) else v},")
                out.append("    },")
            for k, v in (rule.get("fields") or {}).items():
                out.append(f"    {k} = {_lua_str(v) if not _is_lua_literal(v) else v},")
            out.append("})")
            out.append("")

    return "\n".join(out) + "\n"


_LITERAL_RE = re.compile(r"^(true|false|-?\d+(\.\d+)?)$")


def _is_lua_literal(v: str) -> bool:
    return bool(_LITERAL_RE.match(v.strip()))
