"""Idempotently makes sure hyprland.lua sources our generated config, without
touching anything else in the user's file. hl.config()/hl.monitor()/etc.
calls apply in file order, and later calls override earlier ones for
scalar options - so requiring hyprgui at the very END of hyprland.lua means
this app's settings win if they overlap with something already in the
user's hand-written config, matching how the GUI's "current value" always
reflects what will actually be live.
"""
from pathlib import Path

HYPRLAND_LUA = Path.home() / ".config/hypr/hyprland.lua"
HYPRGUI_LUA = Path.home() / ".config/hypr/hyprgui.lua"
MARKER = 'require("hyprgui")'
BLOCK = (
    "\n"
    "-- Added by hyprgui (https://github.com/) - loads settings managed by the\n"
    "-- Hyprland Settings app. Keep this near the end of the file so hyprgui's\n"
    "-- changes take effect even if you also set the same options above.\n"
    f'{MARKER}\n'
)


def ensure_required() -> bool:
    """Returns True if hyprland.lua now requires hyprgui (inserting the line
    if needed), False if hyprland.lua doesn't exist and couldn't be checked.
    """
    if not HYPRLAND_LUA.exists():
        return False
    if not HYPRGUI_LUA.exists():
        # Must exist before the require line is ever loaded/reloaded, or
        # Hyprland's Lua require() fails with "module 'hyprgui' not found"
        # the moment hyprland.lua is (re)loaded - before the user has
        # touched anything in the GUI.
        HYPRGUI_LUA.write_text("-- AUTO-GENERATED by hyprgui. Do not hand-edit.\n")
    text = HYPRLAND_LUA.read_text()
    if MARKER in text:
        return True
    with HYPRLAND_LUA.open("a") as f:
        f.write(BLOCK)
    return True
