#!/usr/bin/env python3
"""Parses Hyprland's own generated Lua type manifest (meta/hl.meta.lua) into
app/schema.py — a plain data table of every hl.config() option, its type,
and a sensible widget kind. Re-run this after a Hyprland upgrade to pick up
newly added options; it is not imported by the running app.
"""
import re
import sys
from pathlib import Path

META_PATH = Path(sys.argv[1] if len(sys.argv) > 1 else
                  Path.home() / "hyprbuntu/Hyprland/meta/hl.meta.lua")
OUT_PATH = Path(__file__).resolve().parent.parent / "app" / "schema.py"

FIELD_RE = re.compile(r"^---@field \['([\w.]+)'\]\s+(.+)$")

SECTION_LABELS = {
    "general": "General",
    "decoration": "Decoration",
    "animations": "Animations",
    "input": "Input",
    "gestures": "Gestures",
    "group": "Group",
    "misc": "Misc",
    "binds": "Binds",
    "cursor": "Cursor",
    "dwindle": "Dwindle Layout",
    "master": "Master Layout",
    "scrolling": "Scrolling Layout",
    "layout": "Layout (General)",
    "xwayland": "XWayland",
    "opengl": "OpenGL",
    "render": "Render",
    "ecosystem": "Ecosystem",
    "experimental": "Experimental",
    "input_capture": "Input Capture",
    "quirks": "Quirks",
    "debug": "Debug",
}


def widget_kind(type_str: str) -> str:
    t = type_str.strip()
    if t == "boolean":
        return "bool"
    if t in ("integer|boolean", "integer"):
        return "int"
    if t in ("number|boolean", "number"):
        return "float"
    if t == "HL.CssGap":
        return "cssgap"
    if t == "HL.Vec2Like":
        return "vec2"
    if "HL.Gradient" in t:
        return "color"
    if t in ("string", "integer|string"):
        return "string"
    return "string"


def main() -> None:
    text = META_PATH.read_text()
    options = []
    for line in text.splitlines():
        m = FIELD_RE.match(line.strip())
        if not m:
            continue
        key, type_str = m.group(1), m.group(2)
        parts = key.split(".")
        section = parts[0]
        group = ".".join(parts[1:-1])
        leaf = parts[-1]
        options.append({
            "key": key,
            "section": section,
            "group": group,
            "leaf": leaf,
            "type": type_str,
            "widget": widget_kind(type_str),
        })

    if not options:
        raise SystemExit(f"No options parsed from {META_PATH} — check the file exists/format changed.")

    sections = sorted({o["section"] for o in options})
    unlabeled = [s for s in sections if s not in SECTION_LABELS]
    if unlabeled:
        print(f"warning: no display label for sections {unlabeled}, using titlecase", file=sys.stderr)

    lines = [
        '"""Auto-generated by scripts/gen_schema.py from Hyprland\'s meta/hl.meta.lua. Do not hand-edit."""',
        "",
        "SECTION_LABELS = {",
    ]
    for s in sections:
        label = SECTION_LABELS.get(s, s.replace("_", " ").title())
        lines.append(f"    {s!r}: {label!r},")
    lines.append("}")
    lines.append("")
    lines.append("OPTIONS = [")
    for o in options:
        lines.append(
            "    {"
            f"'key': {o['key']!r}, 'section': {o['section']!r}, 'group': {o['group']!r}, "
            f"'leaf': {o['leaf']!r}, 'type': {o['type']!r}, 'widget': {o['widget']!r}"
            "},"
        )
    lines.append("]")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines))
    print(f"Wrote {len(options)} options across {len(sections)} sections to {OUT_PATH}")


if __name__ == "__main__":
    main()
